/**
 * Icon Utilities
 * 
 * Helper functions for icon selection and mapping
 */

import { 
  LayoutDashboard, 
  Dumbbell, 
  Apple, 
  Users, 
  UserCircle, 
  Flame,
  Settings,
  Link2,
  FileText,
  LucideIcon,
  type Icon,
  // Additional icons for expanded library
  Calendar,
  Clock,
  Mail,
  Phone,
  MessageSquare,
  BarChart3,
  PieChart,
  TrendingUp,
  Wallet,
  ShoppingCart,
  Package,
  Box,
  Folder,
  FolderOpen,
  Database,
  Server,
  Globe,
  Map,
  Navigation,
  Target,
  Award,
  Star,
  Heart,
  Zap,
  Lightning,
  Sun,
  Moon,
  Cloud,
  Home,
  Building,
  Building2,
  Briefcase,
  CreditCard,
  Receipt,
  List,
  Grid,
  Layout,
  Menu,
  CheckSquare,
  Clipboard,
  Bell,
  Search,
  Filter,
  Download,
  Upload,
  Share2,
  Edit,
  Trash2,
} from 'lucide-react';

// Map of icon names to Lucide icon components
export const ICON_MAP: Record<string, LucideIcon> = {
  'LayoutDashboard': LayoutDashboard,
  'Dumbbell': Dumbbell,
  'Apple': Apple,
  'Users': Users,
  'UserCircle': UserCircle,
  'Flame': Flame,
  'Settings': Settings,
  'Link2': Link2,
  'FileText': FileText,
  'Calendar': Calendar,
  'Clock': Clock,
  'Mail': Mail,
  'Phone': Phone,
  'MessageSquare': MessageSquare,
  'BarChart3': BarChart3,
  'PieChart': PieChart,
  'TrendingUp': TrendingUp,
  'Wallet': Wallet,
  'ShoppingCart': ShoppingCart,
  'Package': Package,
  'Box': Box,
  'Folder': Folder,
  'FolderOpen': FolderOpen,
  'Database': Database,
  'Server': Server,
  'Globe': Globe,
  'Map': Map,
  'Navigation': Navigation,
  'Target': Target,
  'Award': Award,
  'Star': Star,
  'Heart': Heart,
  'Zap': Zap,
  'Sun': Sun,
  'Moon': Moon,
  'Cloud': Cloud,
  'Home': Home,
  'Building': Building,
  'Building2': Building2,
  'Briefcase': Briefcase,
  'CreditCard': CreditCard,
  'Receipt': Receipt,
  'List': List,
  'Grid': Grid,
  'Layout': Layout,
  'Menu': Menu,
  'CheckSquare': CheckSquare,
  'Clipboard': Clipboard,
  'Bell': Bell,
  'Search': Search,
  'Filter': Filter,
  'Download': Download,
  'Upload': Upload,
  'Share2': Share2,
  'Edit': Edit,
  'Trash2': Trash2,
};

// Get default icon for a resource key (matches the navigationItems defaults)
export const getDefaultIconForResourceKey = (resourceKey: string): LucideIcon => {
  const defaultIcons: Record<string, LucideIcon> = {
    'leads': LayoutDashboard, // Match sidebar default
    'customers': LayoutDashboard, // Match sidebar default
    'templates': Dumbbell,
    'nutrition_templates': Apple, // Match sidebar default (not Flame)
    'interfaces': Link2,
    'pages': FileText,
    'settings': Settings,
  };
  
  return defaultIcons[resourceKey] || LayoutDashboard;
};

// Get icon by name string, fallback to default for resource key
export const getIconByName = (iconName: string | null | undefined, resourceKey: string): LucideIcon => {
  if (iconName && iconName in ICON_MAP) {
    return ICON_MAP[iconName];
  }
  return getDefaultIconForResourceKey(resourceKey);
};

// Get all available icon options for selection (expanded library)
export const getAvailableIcons = (): Array<{ name: string; component: LucideIcon; label: string }> => {
  return [
    { name: 'LayoutDashboard', component: LayoutDashboard, label: 'לוח בקרה' },
    { name: 'Users', component: Users, label: 'משתמשים' },
    { name: 'UserCircle', component: UserCircle, label: 'משתמש' },
    { name: 'Dumbbell', component: Dumbbell, label: 'אימונים' },
    { name: 'Flame', component: Flame, label: 'תזונה' },
    { name: 'Apple', component: Apple, label: 'תפוח' },
    { name: 'FileText', component: FileText, label: 'מסמך' },
    { name: 'Link2', component: Link2, label: 'קישור' },
    { name: 'Settings', component: Settings, label: 'הגדרות' },
    { name: 'Calendar', component: Calendar, label: 'לוח שנה' },
    { name: 'Clock', component: Clock, label: 'שעון' },
    { name: 'Mail', component: Mail, label: 'מייל' },
    { name: 'Phone', component: Phone, label: 'טלפון' },
    { name: 'MessageSquare', component: MessageSquare, label: 'הודעות' },
    { name: 'BarChart3', component: BarChart3, label: 'גרף עמודות' },
    { name: 'PieChart', component: PieChart, label: 'עוגה' },
    { name: 'TrendingUp', component: TrendingUp, label: 'מגמה' },
    { name: 'Wallet', component: Wallet, label: 'ארנק' },
    { name: 'ShoppingCart', component: ShoppingCart, label: 'עגלה' },
    { name: 'Package', component: Package, label: 'חבילה' },
    { name: 'Box', component: Box, label: 'קופסה' },
    { name: 'Folder', component: Folder, label: 'תיקייה' },
    { name: 'FolderOpen', component: FolderOpen, label: 'תיקייה פתוחה' },
    { name: 'Database', component: Database, label: 'מסד נתונים' },
    { name: 'Server', component: Server, label: 'שרת' },
    { name: 'Globe', component: Globe, label: 'גלובוס' },
    { name: 'Map', component: Map, label: 'מפה' },
    { name: 'Navigation', component: Navigation, label: 'ניווט' },
    { name: 'Target', component: Target, label: 'יעד' },
    { name: 'Award', component: Award, label: 'פרס' },
    { name: 'Star', component: Star, label: 'כוכב' },
    { name: 'Heart', component: Heart, label: 'לב' },
    { name: 'Zap', component: Zap, label: 'ברק' },
    { name: 'Sun', component: Sun, label: 'שמש' },
    { name: 'Moon', component: Moon, label: 'ירח' },
    { name: 'Cloud', component: Cloud, label: 'ענן' },
    { name: 'Home', component: Home, label: 'בית' },
    { name: 'Building', component: Building, label: 'בניין' },
    { name: 'Building2', component: Building2, label: 'בניין 2' },
    { name: 'Briefcase', component: Briefcase, label: 'תיק' },
    { name: 'CreditCard', component: CreditCard, label: 'אשראי' },
    { name: 'Receipt', component: Receipt, label: 'קבלה' },
    { name: 'List', component: List, label: 'רשימה' },
    { name: 'Grid', component: Grid, label: 'רשת' },
    { name: 'Layout', component: Layout, label: 'פריסה' },
    { name: 'Menu', component: Menu, label: 'תפריט' },
    { name: 'CheckSquare', component: CheckSquare, label: 'סימון' },
    { name: 'Clipboard', component: Clipboard, label: 'לוח' },
    { name: 'Bell', component: Bell, label: 'פעמון' },
    { name: 'Search', component: Search, label: 'חיפוש' },
    { name: 'Filter', component: Filter, label: 'סינון' },
    { name: 'Download', component: Download, label: 'הורדה' },
    { name: 'Upload', component: Upload, label: 'העלאה' },
    { name: 'Share2', component: Share2, label: 'שיתוף' },
    { name: 'Edit', component: Edit, label: 'עריכה' },
    { name: 'Trash2', component: Trash2, label: 'מחיקה' },
  ];
};

